### ISSUE TITLE
udp_recv error

### ISSUE THREAD

**Issue by XiaoWZENG** [ZiwenZhuang/parkour#10]
When I used the go1 for Sim2Real, the error shows "udp_recv error: -3, message translate might lost once". Is the problem caused by the wrong SDK version? The SDK 3.3.1 is not support for go1.

**Comment by ZiwenZhuang** [comment]
Please use [go1 branch on unitree_ros_real](https://github.com/Tsinghua-MARS-Lab/unitree_ros_real/tree/go1)

v3.3.1 is only used in unitree_ros_real for A1.

Best,

**Comment by XiaoWZENG** [comment]
Ok, thanks a lot.
