### ISSUE TITLE
Cmd lost, position control as motor damping. DO NOT use this as a normal operation

### ISSUE THREAD

**Issue by P1terQ** [ZiwenZhuang/parkour#14]
Great work and thanks for your opensource! 

I want to test the onboard code on A1 and downloaded unitree_legged_sdk v3.3.1. The problem is **as long as i roslaunch unitree_legged_real robot.launch， the warn comes out  `[ WARN] [1701523939.918416399]: Cmd lost, position control as motor damping. DO NOT use this as a normal operation.`** 

Here is the complete info in the terminal:

... logging to /home/ustc/.ros/log/209d6ec8-904e-11ee-9d14-0d79cc269739/roslaunch-dell5820-1436634.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://127.0.0.1:42471/

SUMMARY
========

PARAMETERS
 * /a112138/R2_press_protect: True
 * /a112138/cmd_check: True
 * /a112138/cmd_lost_timelimit: 0.05
 * /a112138/ctrl_level: low
 * /a112138/dryrun: True
 * /a112138/freeze_lost: False
 * /a112138/pitch_protect_limit: 1.3
 * /a112138/position_protect_limit: 0.0
 * /a112138/power_protect_level: 8
 * /a112138/publish_imu: False
 * /a112138/publish_joint_state: False
 * /a112138/publish_wirelessRemote: False
 * /a112138/roll_protect_limit: 0.9
 * /a112138/start_stand: False
 * /a112138/torque_protect_limit: 38.0
 * /a112138/udp_duration: 0.01
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    a112138 (unitree_legged_real/real_robot)

ROS_MASTER_URI=http://127.0.0.1:11311

process[a112138-1]: started with pid [1436675]
UDP Initialized. Port: 8080 
[ INFO] [1701523939.860609570]: Motor will be initialized to mode 0, please put the robot on the ground or hang up.
[ INFO] [1701523939.861923790]: Udp initialized
[Loop Start] named: udp_recv, period: 9(ms), run at cpu: 3 
[Loop Start] named: udp_send, period: 9(ms), run at cpu: 3 
[Loop Start] named: udp_translate, period: 9(ms), cpu unspecified
[ INFO] [1701523939.868134807]: RosUdpHandler constructed and started
[ WARN] [1701523939.918416399]: Cmd lost, position control as motor damping. DO NOT use this as a normal operation.
[ WARN] [1701523969.968446309]: Cmd lost, position control as motor damping. DO NOT use this as a normal operation.

Looking forward to your reply!

**Comment by ZiwenZhuang** [comment]
Hi,

Don't worry about this warning. This message is designed to let you know the ROS node is running and does not receive any command from the system. You should either terminate the ROS node to prevent unexpected behavior or launch the policy in your next step.

Best,
