### ISSUE TITLE
Uncertainty about the training process

### ISSUE THREAD

**Issue by wut19** [ZiwenZhuang/parkour#18]
I'm new to train a locomotion task. And the training process is complex. I have followed #3 to train the policy. But I still have some confusion on the training results. For example, I have tried to train the walk policy several times but it turned out to work badly as I used play.py to visualize the trained policy. And the walk policy training part is not mentioned in this paper so I'm wondering the training of walk is just a warmup or the result should be good. And should I just follow the steps in #3 ? Are there any ways to determine whether the training is useful so that I can relax the constraints or some other parameters to make the training process successful?

**Comment by ZiwenZhuang** [comment]
Training a good walking policy before the soft dynamics constraint stage would be better.

But in theory and based on other people's practice, you may start training all the skills together as long as you get a reasonable walking policy in simulation.

You still need to tune a good and smooth behavior before you deploy it on the real robot.

**Comment by wut19** [comment]
Thanks!
