### ISSUE TITLE
Sim2real transfer, udp_recv error

### ISSUE THREAD

**Issue by Anchoret13** [ZiwenZhuang/parkour#19]
After first build, I was able to run `roslaunch unitree_legged_real robot.launch`, but after restart, I keep getting `udp_recv error: -1 message translate might lost once` and unable to get the info from robot any more. 

Rebuild didn't solve the problem. The sdk version is 3.8.6, and I'm pretty sure all packages were built successfully.

**Comment by ZiwenZhuang** [comment]
Please check whether you used the correct SDK and ROS package for the correct robot model (A1 or Go1)
 
Then, please refer to Unitree's official documentation and check whether you set the robot to the correct mode.

**Comment by Anchoret13** [comment]
Hardware issue, problem solved

**Comment by DecaYale** [comment]
> Hardware issue, problem solved

How do you solve this? Thx.
