### ISSUE TITLE
About RND and Oracles w/o Soft Dyn

### ISSUE THREAD

**Issue by yingchengyang** [ZiwenZhuang/parkour#22]
Thanks a lot for providing such wonderful work and clean codes! I'm curious about the results of RND and Oracles w/o Soft Dyn in Fig.7 and Fig. 9 in the paper (https://robot-parkour.github.io/resources/Robot_Parkour_Learning.pdf). In my opinion, they both directly train in the hard dynamics constraints by PPO and PPO+RND respectively, is that right? Also, Where is the code about RND in this repo?

Thanks again!

**Comment by ZiwenZhuang** [comment]
Yes, both PPO and PPO+RND are trained directly using hard dynamics constraints.

Due to the code structure, the implementation of RND is quite messy in our private repo. Thus, we remove the RND implementation in the public repository.

**Comment by yingchengyang** [comment]
Thanks a lot!
