### ISSUE TITLE
How to train the policy with go1?

### ISSUE THREAD

**Issue by hakieh** [ZiwenZhuang/parkour#28]
Hi, in the deploy file you show how to deploy code in go1,but how can i train the policy with go1 in vitural environment?

**Comment by ZiwenZhuang** [comment]
Hi,

All the example config files for Go1 is already in `legged_gym/envs/go1`. You may use these files with the registered task to train your own policy for Go1.

Please refer to `egged_gym/legged_gym/envs/__init__.py` and check the corresponding task for each config file.

Please noted that, the configs for Go1 does not garantee the successful training from scratch. You may need to tryout different reward formulations.

**Comment by hakieh** [comment]
thanks for reply！
