### ISSUE TITLE
Why mounting extra camera on Go1 robot

### ISSUE THREAD

**Issue by JerryXu0907** [ZiwenZhuang/parkour#34]
Hi,

Thank you very much for open-sourcing such a wonderful project. I have a simple question regarding the realsense camera you are using on Go1 robots. From the videos on your webpage, I don't think you mount cameras on A1 robots, so why mounting on Go1 robots? Is there something wrong with the onboard RGBD camera, or you are trying to mimic the A1 camera, or you just find out different viewing angle can help a lot for parkour?

Thanks a lot!

**Comment by terry97-guel** [comment]
Hi! 
I was wondering the same thing.

It seems that this issue, as @JerryXu0907 figured it out.
Could you share your thoughts on this?
