### ISSUE TITLE
Sudden termination of code execution

### ISSUE THREAD

**Issue by chenci107** [ZiwenZhuang/parkour#4]
Thank you for opening up your code.
My code suddenly terminates at a certain moment and displays "segment error (core has been dumped)", and the interruption time is also quite random. What is the problem? How should we solve it?  Thanks~
![image](https://github.com/ZiwenZhuang/parkour/assets/48233618/c02600c7-45be-4ca9-9f28-5936dc252dc4)

**Comment by ZiwenZhuang** [comment]
Hi, did you check your memory usage? It is likely that the program reaches the limit of the GPU memory or the main memory.

**Comment by chenci107** [comment]
Thank you for your reply. My memory capacity is 32G, the GPU used is 3080ti, and the number of parallel environments opened is 2048. I am going to use the 3090 GPU to test.

**Comment by ZiwenZhuang** [comment]
No problem! Typically 3080 (10G) for training 2048 robots in parallel is not enough.
