### ISSUE TITLE
Re-trying behaviour

### ISSUE THREAD

**Issue by Ekaterinador** [ZiwenZhuang/parkour#41]
Hello, thank you for your excellent open source work!

I noticed in the video that the robot keeps re-tryinng as it climbs. I would be grateful if you could tell me how you achieved this behaviour? 
I'm now trying to train the Go2 robot using your repository. If the robot fails to climb the first time, it just stands in front of the obstacle and does not try again.

**Comment by ZiwenZhuang** [comment]
Hi,

As for the retrying behavior as it climbs, it emerges automatically, we did not add any specific tunning to this task. The key point is to let the robot see if following the velocity command produces a higher return than simply staying and keeping alive.

For a more detailed explanation of the danger-avoiding action, you may refer to (this paper)[https://sites.google.com/leggedrobotics.com/risk-aware-locomotion]

**Comment by Ekaterinador** [comment]
Thank you!
