### ISSUE TITLE
Question about deploying on Go2.

### ISSUE THREAD

**Issue by change-every** [ZiwenZhuang/parkour#47]
Thanks for your excellent code framework!
I have a concern if I want to deploy the code on Go2. Can I follow the instructions on the simulation? And what is the difference in deployment between Go1 and Go2? Is it just the SDK?
Thank you very much!

**Comment by ZiwenZhuang** [comment]
Since I wrote a ROS 1 package for A1's deployment, you may deploy a well-trained model using this repo on Go2 in a similar way. But in ROS 2 fashion.

Thus, I would recommend rewrite the deployment script. The model part does not need any re-implementation.

**Comment by change-every** [comment]
Thanks!!!
